Add test report in GH

diff --git a/.github/workflows/git_ci_cd.yml b/.github/workflows/git_ci_cd.yml
--- a/.github/workflows/git_ci_cd.yml
+++ b/.github/workflows/git_ci_cd.yml
@@ -1,10 +1,6 @@
 name: Building CI/CD mipaquete
 run-name: ${{ github.actor }} is testing mipaquete 🚀
 on: [push]
-# on:
-#   push: #Esto se ejecuta solo cuando hay un tag
-#     tags:
-#       - "v*.*.*"
 jobs:
   building_mipaquete:
     runs-on: ubuntu-latest
@@ -15,9 +11,6 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: '3.10'
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
       - name: Check hola() function
         run: python -m mipaquete
       - name: Install Poetry
@@ -25,7 +18,14 @@ jobs:
       - name: Install dependecies
         run: poetry install
       - name: Testing
-        run: poetry run pytest
+        run: poetry run pytest --junitxml=jest-junit.xml
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Tests with reports            # Name of the check run which will be created
+          path: jest-junit.xml    # Path to test results
+          reporter: java-junit        # Format of test results
       - name: Build mipaquete
         run: poetry build
       - name: Publish Release to GH
@@ -33,6 +33,9 @@ jobs:
         uses: softprops/action-gh-release@v1
         with:
           files: ${{ github.workspace }}/dist/*
+      - name: List files in the repository
+        run: |
+          ls ${{ github.workspace }}
       
 
 
